In [2]:
# !pip install koreanize-matplotlib
import koreanize_matplotlib

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path = '../../data/Airbnb_London/listings.csv'

In [4]:
df = pd.read_csv(path)
df = pd.DataFrame(df)

In [5]:
dat = df.copy()

<h3>필요한 컬럼 가져오기(24개) + property_type <h3>

In [6]:
#필요한 컬럼 가져오기
selected_columns = ['id','listing_url','host_id', 'property_type', 'number_of_reviews_ltm',
                    'host_is_superhost','host_total_listings_count','neighbourhood_cleansed','latitude',
                    'longitude','room_type','accommodates','bathrooms','bedrooms','beds','amenities','price',
                    'minimum_nights','maximum_nights','number_of_reviews','number_of_reviews_l30d',
                    'review_scores_rating','review_scores_accuracy','review_scores_cleanliness',
                    'review_scores_checkin','review_scores_communication','review_scores_location',
                    'review_scores_value','reviews_per_month']
df = df[selected_columns]

df.head(3)

,id,listing_url,host_id,property_type,number_of_reviews_ltm,host_is_superhost,host_total_listings_count,neighbourhood_cleansed,latitude,longitude,...,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,312761,https://www.airbnb.com/rooms/312761,1608226,Entire rental unit,26,t,3.0,Hackney,51.52704,-0.08129,...,122,0,4.96,4.97,4.93,4.96,5.00,4.89,4.93,0.86
1,13913,https://www.airbnb.com/rooms/13913,54730,Private room in rental unit,1,t,5.0,Islington,51.56861,-0.11270,...,41,0,4.80,4.73,4.73,4.75,4.83,4.70,4.70,0.25
2,15400,https://www.airbnb.com/rooms/15400,60302,Entire rental unit,2,f,1.0,Kensington and Chelsea,51.48780,-0.16813,...,94,0,4.80,4.85,4.88,4.88,4.83,4.93,4.74,0.54

<h3>필요한 컬럼명 변경</h3><br>


컬렴명 변경

- 'id' : '숙소 id'
- 'property_type' : '숙소_특징'
- 'listing_url' : '숙소 url'
- 'host_id' : '호스트 id'
- 'host_is_superhost' : '슈퍼호스트 여부'
- 'latitude' : '위도'
- 'longitude' : '경도'
- 'host_total_listings_count' : '등록한 총 숙소 수'
- 'neighbourhood_cleansed' : '클린된 숙소 구'
- 'room_type' : '룸 유형'
- 'accommodates' : '수용 인원수'
- 'bathrooms' : '욕실수'
- 'bedrooms' : '침실수'
- 'beds' : '침대수'
- 'amenities' : '어메니티'
- 'price' : '숙소 가격'
- 'minimum_nights' : '최소 숙박일'
- 'maximum_nights' : '최대 숙박일'
- 'number_of_reviews' : '총 리뷰수'
- 'number_of_reviews_l30d' : '한달치 리뷰수'
- 'review_scores_rating' : '리뷰 총점수'
- 'review_scores_accuracy' : '리뷰점수(숙소정보 정확성 )'
- 'review_scores_cleanliness' : '리뷰점수(청결함)'
- 'review_scores_checkin' : '리뷰점수(체크인과정)'
- 'review_scores_communication' : '리뷰점수(호스트와 소통)'
- 'review_scores_location' : '리뷰점수(숙소위치)'
- 'review_scores_value' : '리뷰점수(숙소가격)'
- 'reviews_per_month' : '월별 평균 리뷰수'

In [7]:
#컬럼명 변경
df = df.rename(columns={
    'id' : '숙소_id',
    'listing_url' : '숙소_url',
    'property_type' : '숙소_특징',
    'host_id' : '호스트_id',
    'host_is_superhost' : '슈퍼호스트',
    'host_total_listings_count' : '숙소_수',
    'neighbourhood_cleansed' : '숙소_지역',
    'latitude' : '위도',
    'longitude' : '경도',
    'room_type' : '숙소_유형',
    'accommodates' : '수용인원수',
    'bathrooms' : '욕실수',
    'bedrooms' : '침실수',
    'beds' : '침대수',
    'amenities' : '어메니티',
    'price' : '숙소_가격',
    'minimum_nights' : '최소_숙박일',
    'maximum_nights' : '최대_숙박일',
    'minimum_maximum_nights' : '적은_최대_숙박일',
    'maximum_maximum_nights' : '많은_최대_숙박일',
    'has_availability' : '숙소_예약가능_여부',
    'number_of_reviews' : '리뷰수',
    'number_of_reviews_l30d' : '30일_리뷰수',
    'review_scores_rating' : '리뷰점수',
    'review_scores_accuracy' : '숙소_정확성_리뷰점수',
    'review_scores_cleanliness' : '숙소_청결도_리뷰점수',
    'review_scores_checkin' : '숙소_체크인_리뷰점수',
    'review_scores_communication' : '숙소_소통_리뷰점수',
    'review_scores_location' : '숙소_위치_리뷰점수',
    'review_scores_value' : '숙소_가격_리뷰점수',
    'reviews_per_month' : '평균_리뷰수',
    'number_of_reviews_ltm' : '12개월_리뷰수'
})

<h3>주제별 컬럼 분류<h3><br>

숙소/숙박 컬럼 (25개) df_lodging - 리뷰 컬럼(10개) df_review

In [8]:
#숙소/숙박관련 컬럼

df_lodging = dat[['id', 'listing_url','host_id','host_is_superhost','property_type',
                  'host_total_listings_count','neighbourhood_cleansed','room_type','accommodates','bathrooms','bedrooms',
                  'beds','amenities','price','minimum_nights','maximum_nights']]
df_lodging.head(3)

,id,listing_url,host_id,host_is_superhost,property_type,host_total_listings_count,neighbourhood_cleansed,room_type,accommodates,bathrooms,bedrooms,beds,amenities,price,minimum_nights,maximum_nights
0,312761,https://www.airbnb.com/rooms/312761,1608226,t,Entire rental unit,3.0,Hackney,Entire home/apt,2,1.0,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Coffee m...",$160.00,9,180
1,13913,https://www.airbnb.com/rooms/13913,54730,t,Private room in rental unit,5.0,Islington,Private room,1,1.0,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Shampoo""...",$65.00,1,29
2,15400,https://www.airbnb.com/rooms/15400,60302,f,Entire rental unit,1.0,Kensington and Chelsea,Entire home/apt,2,1.0,1.0,1.0,"[""Shampoo"", ""Wifi"", ""Fire extinguisher"", ""Lugg...",$120.00,4,30

In [9]:
# 컬럼명 변경

df_lodging = df_lodging.rename(columns={
    'id': '숙소_id',
    'host_id': '호스트_id',
    'property_type' : '숙소_특징',
    'listing_url' : '숙소_url',
    'host_is_superhost': '슈퍼호스트',
    'host_total_listings_count': '숙소_수',
    'neighbourhood_cleansed': '숙소_지역',
    'room_type': '숙소_유형',
    'accommodates': '수용인원수',
    'bathrooms': '욕실수',
    'bedrooms': '침실수',
    'beds': '침대수',
    'amenities': '편의시설',
    'price': '숙소_가격',
    'minimum_nights': '최소_숙박일',
    'maximum_nights': '최대_숙박일'
})

df_lodging.head(3)

,숙소_id,숙소_url,호스트_id,슈퍼호스트,숙소_특징,숙소_수,숙소_지역,숙소_유형,수용인원수,욕실수,침실수,침대수,편의시설,숙소_가격,최소_숙박일,최대_숙박일
0,312761,https://www.airbnb.com/rooms/312761,1608226,t,Entire rental unit,3.0,Hackney,Entire home/apt,2,1.0,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Coffee m...",$160.00,9,180
1,13913,https://www.airbnb.com/rooms/13913,54730,t,Private room in rental unit,5.0,Islington,Private room,1,1.0,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Shampoo""...",$65.00,1,29
2,15400,https://www.airbnb.com/rooms/15400,60302,f,Entire rental unit,1.0,Kensington and Chelsea,Entire home/apt,2,1.0,1.0,1.0,"[""Shampoo"", ""Wifi"", ""Fire extinguisher"", ""Lugg...",$120.00,4,30

In [10]:
#리뷰관련데이터
df_review = dat[['listing_url','number_of_reviews', 'number_of_reviews_l30d', 'review_scores_rating', 'review_scores_accuracy',
                'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication',
                'review_scores_location', 'review_scores_value', 'reviews_per_month','number_of_reviews_ltm']]
df_review.head(3)

,listing_url,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,number_of_reviews_ltm
0,https://www.airbnb.com/rooms/312761,122,0,4.96,4.97,4.93,4.96,5.00,4.89,4.93,0.86,26
1,https://www.airbnb.com/rooms/13913,41,0,4.80,4.73,4.73,4.75,4.83,4.70,4.70,0.25,1
2,https://www.airbnb.com/rooms/15400,94,0,4.80,4.85,4.88,4.88,4.83,4.93,4.74,0.54,2

In [11]:
# 컬럼명 변경
df_review = df_review.rename(columns={
    'listing_url' : '숙소_url',
    'number_of_reviews': '리뷰수',
    'number_of_reviews_l30d': '30일_리뷰수',
    'review_scores_rating': '리뷰점수',
    'review_scores_accuracy': '숙소_정확성_리뷰점수',
    'review_scores_cleanliness': '숙소_청결도_리뷰점수',
    'review_scores_checkin': '숙소_체크인_리뷰점수',
    'review_scores_communication': '숙소_소통_리뷰점수',
    'review_scores_location': '숙소_위치_리뷰점수',
    'review_scores_value': '숙소_가격_리뷰점수',
    'reviews_per_month': '평균_리뷰수',
    'number_of_reviews_ltm' : '12개월_리뷰수'
})
df_review.head()

,숙소_url,리뷰수,30일_리뷰수,리뷰점수,숙소_정확성_리뷰점수,숙소_청결도_리뷰점수,숙소_체크인_리뷰점수,숙소_소통_리뷰점수,숙소_위치_리뷰점수,숙소_가격_리뷰점수,평균_리뷰수,12개월_리뷰수
0,https://www.airbnb.com/rooms/312761,122,0,4.96,4.97,4.93,4.96,5.00,4.89,4.93,0.86,26
1,https://www.airbnb.com/rooms/13913,41,0,4.80,4.73,4.73,4.75,4.83,4.70,4.70,0.25,1
2,https://www.airbnb.com/rooms/15400,94,0,4.80,4.85,4.88,4.88,4.83,4.93,4.74,0.54,2
3,https://www.airbnb.com/rooms/159736,96,0,4.72,4.79,4.66,4.75,4.89,4.34,4.66,0.62,1
4,https://www.airbnb.com/rooms/165336,237,2,4.74,4.88,4.79,4.94,4.96,4.87,4.71,1.57,25

In [12]:
df_lodging.shape

(90852, 16)

In [13]:
df_review.shape

(90852, 12)

In [14]:
df.shape

(90852, 29)

In [15]:
df.dtypes

숙소_id            int64
숙소_url          object
호스트_id           int64
숙소_특징           object
12개월_리뷰수         int64
슈퍼호스트           object
숙소_수           float64
숙소_지역           object
위도             float64
경도             float64
숙소_유형           object
수용인원수            int64
욕실수            float64
침실수            float64
침대수            float64
어메니티            object
숙소_가격           object
최소_숙박일           int64
최대_숙박일           int64
리뷰수              int64
30일_리뷰수          int64
리뷰점수           float64
숙소_정확성_리뷰점수    float64
숙소_청결도_리뷰점수    float64
숙소_체크인_리뷰점수    float64
숙소_소통_리뷰점수     float64
숙소_위치_리뷰점수     float64
숙소_가격_리뷰점수     float64
평균_리뷰수         float64
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90852 entries, 0 to 90851
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   숙소_id        90852 non-null  int64
 1   숙소_url       90852 non-null  object
 2   호스트_id       90852 non-null  int64
 3   숙소_특징        90852 non-null  object
 4   12개월_리뷰수     90852 non-null  int64
 5   슈퍼호스트        90463 non-null  object
 6   숙소_수         90847 non-null  float64
 7   숙소_지역        90852 non-null  object
 8   위도           90852 non-null  float64
 9   경도           90852 non-null  float64
 10  숙소_유형        90852 non-null  object
 11  수용인원수        90852 non-null  int64
 12  욕실수          57894 non-null  float64
 13  침실수          78118 non-null  float64
 14  침대수          57837 non-null  float64
 15  어메니티         90852 non-null  object
 16  숙소_가격        57885 non-null  object
 17  최소_숙박일       90852 non-null  int64
 18  최대_숙박일       90852 non-null  int64
 19  리뷰수          90852 non-null  int64
 20  30일_리뷰수      90852 non-null  int64
 21  리뷰점수         65869 non-null  float64
 22  숙소_정확성_리뷰점수  65838 non-null  float64
 23  숙소_청결도_리뷰점수  65843 non-null  float64
 24  숙소_체크인_리뷰점수  65808 non-null  float64
 25  숙소_소통_리뷰점수   65833 non-null  float64
 26  숙소_위치_리뷰점수   65808 non-null  float64
 27  숙소_가격_리뷰점수   65806 non-null  float64
 28  평균_리뷰수       65869 non-null  float64
dtypes: float64(14), int64(8), object(7)
memory usage: 20.1+ MB

<h3>결측치 개수</h3><br>

- 슈퍼호스트 389개
- 문의_응답률 33,055개
- 숙소_수 5개
- 욕실수 32,958개
- 침실수 12,734개
- 침대수 33,015개
- 숙소_가격 32,967개
- 리뷰점수 24,983개
- 숙소_정확성_리뷰점수 25014개
- 숙소_청결도_리뷰점수 25009개
- 숙소_체크인_리뷰점수 25044개
- 숙소_소통_리뷰점수 25019개
- 숙소_위치_리뷰점수 25044개
- 숙소_가격_리뷰점수 25046개
- 평균_리뷰수 24983개

- -----------------------------------------

- 숙소_상세설명 3,001개
- 프로필사진_소지_여부 5개
- 신원_검증_여부 5개
- 숙소_예약가능_여부 4079개

결측치 제거 확정 <br>
- 슈퍼호스트 null값 (389개) 5%이하
- 리뷰수 = 0인 값 --> 리뷰수가 없으면 리뷰점수도 없다
- 숙소수 null값 (5개)
- 리뷰분야 6개 전부 nan값인 컬럼
- 리뷰수 = 1 인값

In [20]:
# 슈퍼호스트, 리뷰수 결측치 제거
print(f"처음 df : {len(df)}")
df = df[~df['슈퍼호스트'].isnull()]
print(f"슈퍼호스트 제거 : {len(df)}")
df = df[df['리뷰수']!=0]
print(f"리뷰수 제거 : {len(df)}")

# #숙소가격 null값 제거
check1= df[~df['숙소_가격'].isnull()]

#가격 앞 통화기호 제거
check1['숙소_가격'] = check1['숙소_가격'].replace('[\$,]', '', regex=True).astype(float)

# 욕실수,침대수,침실수 결측치 제거
print(f"욕실,침대,침실 수 제거 전 : {len(check1)}")
check1 = check1.dropna(subset=['욕실수', '침실수', '침대수'])
print(f"제거 후 : {len(check1)}")

# 유형 제거 
check1 = check1[(check1['숙소_유형']=='Entire home/apt') | (check1['숙소_유형']=='Private room')]
print(f"숙소_유형 제거 : {len(check1)}")

# 12개월 리뷰수 0 개 제거
df = df[df['12개월_리뷰수']!=0]
print(f"12개월_리뷰수 0개 제거 : {len(df)}")

처음 df : 65538
슈퍼호스트 제거 : 65538
리뷰수 제거 : 65538
욕실,침대,침실 수 제거 전 : 43462
제거 후 : 43355
숙소_유형 제거 : 43091

C:\Users\Master\AppData\Local\Temp\ipykernel_12960\30150074.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  check1['숙소_가격'] = check1['숙소_가격'].replace('[\$,]', '', regex=True).astype(float)

In [21]:
check1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43091 entries, 0 to 90735
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   숙소_id        43091 non-null  int64
 1   숙소_url       43091 non-null  object
 2   호스트_id       43091 non-null  int64
 3   숙소_특징        43091 non-null  object
 4   12개월_리뷰수     43091 non-null  int64
 5   슈퍼호스트        43091 non-null  object
 6   숙소_수         43091 non-null  float64
 7   숙소_지역        43091 non-null  object
 8   위도           43091 non-null  float64
 9   경도           43091 non-null  float64
 10  숙소_유형        43091 non-null  object
 11  수용인원수        43091 non-null  int64
 12  욕실수          43091 non-null  float64
 13  침실수          43091 non-null  float64
 14  침대수          43091 non-null  float64
 15  어메니티         43091 non-null  object
 16  숙소_가격        43091 non-null  float64
 17  최소_숙박일       43091 non-null  int64
 18  최대_숙박일       43091 non-null  int64
 19  리뷰수          43091 non-null  int64
 20  30일_리뷰수      43091 non-null  int64
 21  리뷰점수         43091 non-null  float64
 22  숙소_정확성_리뷰점수  43075 non-null  float64
 23  숙소_청결도_리뷰점수  43074 non-null  float64
 24  숙소_체크인_리뷰점수  43074 non-null  float64
 25  숙소_소통_리뷰점수   43075 non-null  float64
 26  숙소_위치_리뷰점수   43074 non-null  float64
 27  숙소_가격_리뷰점수   43073 non-null  float64
 28  평균_리뷰수       43091 non-null  float64
dtypes: float64(15), int64(8), object(6)
memory usage: 9.9+ MB

In [22]:
check1.isna().sum()

숙소_id           0
숙소_url          0
호스트_id          0
숙소_특징           0
12개월_리뷰수        0
슈퍼호스트           0
숙소_수            0
숙소_지역           0
위도              0
경도              0
숙소_유형           0
수용인원수           0
욕실수             0
침실수             0
침대수             0
어메니티            0
숙소_가격           0
최소_숙박일          0
최대_숙박일          0
리뷰수             0
30일_리뷰수         0
리뷰점수            0
숙소_정확성_리뷰점수    16
숙소_청결도_리뷰점수    17
숙소_체크인_리뷰점수    17
숙소_소통_리뷰점수     16
숙소_위치_리뷰점수     17
숙소_가격_리뷰점수     18
평균_리뷰수          0
dtype: int64